exports.GET_USER = 'GET_USER'
exports.GET_USER_FROM_STORAGE = 'GET_USER_FROM_STORAGE'
exports.GET_USER_FROM_STORAGE_FAILED = 'GET_USER_FROM_STORAGE_FAILED'
exports.FETCH_USER = 'FETCH_USER'


exports.OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
exports.CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS'
exports.QR_SUCCESS = 'QR_SUCCESS'
exports.CHECK_TOKEN = 'CHECK_TOKEN'
